blank_issues_enabled: false
contact_links:
  - name: GTNewHorizons Discord
    url: https://discord.gg/EXshrPV
    about: >-
      Please ask questions in the #help channel of this discord server.
      
      If none of the templates above suits your need, please ask for help in the #github-discussions channel of this server. 
