name: Report Bug
description: "Report a bug that does not abruptly end a game session or prevent the start of the game."
labels:
- "Status: Triage"
body:
- type: markdown
  attributes:
    value: 'Examples of this category includes: item dupe, item void, can't craft item, behavior and description does not match.

      Please note if you merely want a change, e.g. think something is too OP, you should use the Suggest a Change template instead.
- type: input
  id: discord
  attributes:
    label: Your GTNH Discord Username
    description: We might need to contact you in person if we need additional info
    placeholder: "Example: Fake#1234"
- type: input
  id: version
  attributes:
    label: Your Pack Version
    description: What version of the pack are you playing? If you are using an ancient version maybe first try updating the pack. We usually fix hundreds of issues per release, so there is a good chance your problem have been fixed already in latest.
    placeholder: "Example: 2.1.1.0"
  validations:
    required: true
- type: input
  id: server
  attributes:
    label: Your Server
    description: On which server does this happen? Type SP if you are not playing on a dedicated server.
    placeholder: "Example: Eta, ProsperCraft, private server, SP"
  validations:
    required: true
- type: dropdown
  id: thermos
  attributes:
    label: Type of Server
    description: The brand of your server.
    options:
    - Single Player
    - Single Player Open to LAN
    - Vanilla Forge
    - Cruicible
    - Thermos
    - Other MCPC+ fork
    - "Don't know"
- type: textarea
  id: expectation
  attributes:
    label: Your expectation
    description: What did you try to do, and what did you expect to happen?. Attach screenshots if needed.
    placeholder: "Example: Trying to craft Foo. Expect to consume 1 Bar and get 1 Foo."
  validations:
    required: true
- type: textarea
  id: actual
  attributes:
    label: The Reality
    description: What happened instead? Attach screenshots if needed
    placeholder: "Example: 1 Foo is crafted but no Bar is consumed."
  validations:
    required: true
- type: textarea
  id: proposal
  attributes:
    label: Your Proposal
    description: Please describe it breifly in one or two sentence.
    placeholder: "Example: Consume 1 Bar properly."
  validations:
    required: true
- type: checkboxes
  id: final
  attributes:
    label: Final checklist
    description: Please mark them so we can better handle this report
    options:
      - label: "I have searched this issue tracker and there is nothing similar already. (Post on the closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report)"
        required: true
      - label: "I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole."
        required: false
      - label: "I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole."
        required: false
