name: Suggest a change
description: Suggest a change to an existing feature
labels:
- "Status: Triage"
- "Type: suggestion"
body:
- type: markdown
  attributes:
    value: >
    Examples of this category includes: The One Ring too OP, remove all small pile of dusts.
    Please note if you found something game breaking, e.g. a dupe exploit, something void your items, or you can't do something that you think you can be doing, you should use the Report Bug template instead."
- type: input
  id: discord
  attributes:
    label: Your GTNH Discord Username
    description: What is your GTNH Discord username? We might need to contact you in person if we need additional info
    placeholder: "Example: Fake#1234"
- type: input
  id: version
  attributes:
    label: Your Pack Version
    description: What version of the pack are you playing?
    placeholder: "Example: 2.1.1.0"
  validations:
    required: true
- type: textarea
  id: proposal
  attributes:
    label: Your Proposal
    description: What do you propose? Please describe it briefly in one or two sentence.
    placeholder: "Example: Void miner should require stargate crystals to craft."
  validations:
    required: true
- type: textarea
  id: goal
  attributes:
    label: Your Goal
    description: Why is this feature needed?
    placeholder: "Example: Void miner are too OP"
  validations:
    required: true
- type: textarea
  id: vision
  attributes:
    label: Your Vision
    description: How do you vision this would improve the pack?
    placeholder: "Example: Void miner would be made less OP and make people enjoy the pack."
  validations:
    required: true
- type: checkboxes
  id: final
  attributes:
    label: Final checklist
    description: Please mark them so we know you are serious with your suggestion
    options:
      - label: "I have searched this issue tracker and there is nothing similar already. (Post on the closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report)"
        required: true
      - label: "I understand this change request may not attract enough attention and thus not be implemented."
        required: true
      - label: "I understand this change request may be rejected due to other community members think it's inappropriate."
        required: true
      - label: "I believe this feature would make the pack better."
        required: true
        
