name: Create a reminder
description: Often developers tell you to create a ticket as reminder. Choose this one ONLY when instructed to do so.
labels:
- "Status: Triage"
body:
- type: input
  id: discord
  attributes:
    label: Your GTNH Discord Username
    description: What is your GTNH Discord username? We might need to contact you in person if we need additional info
    placeholder: "Example: Fake#1234"
- type: input
  id: version
  attributes:
    label: Your Pack Version
    description: What version of the pack are you playing?
    placeholder: "Example: 2.1.1.0"
  validations:
    required: true
- type: input
  id: request
  attributes:
    label: Original Request
    description: What did you requested?
    placeholder: "Example: Struggling with power generation."
  validations:
    required: true
- type: input
  id: dev
  attributes:
    label: Responding developer
    description: Who responded to your request
    placeholder: "Example: glease."
  validations:
    required: true
- type: textarea
  id: context
  attributes:
    label: Context
    description: Links to discord chat messages.
    placeholder: "Example: https://discord.com/channels/1111111111111111/1111111111111111/1111111111111111, https://discord.com/channels/222222222222222/222222222222222/222222222222222"
  validations:
    required: true
- type: textarea
  id: promise
  attributes:
    label: Developer's promise
    description: What did the developer promised? Please rephrase it in your own language so we know your expectation matches the developers promise.
    placeholder: "Example: glease promised to add a new power generation option based on magic"
  validations:
    required: true
- type: checkboxes
  id: final
  attributes:
    label: Final checklist
    description: Please mark them so we know you are serious with your suggestion
    options:
      - label: "The developer in question has instructed me to create such an issue."
        required: true
      - label: "I believe the developer is not causally joking around."
        required: true
      - label: "I understand this reminder might take a long time to implement no matter what the developer has promised."
        required: true
      - label: "I understand other people (developers or not) might not like this feature and would oppose its integration."
        required: true
      - label: "I believe this feature would make the pack better."
        required: true
